pipeline:
  lint:
    image: node
    commands:
      - npm run lint

  publish:
    image: node
    commands:
      - git fetch --tags --quiet origin
      - npx semantic-release
    secrets: [ gh_token, npm_token ]
    when:
      branch: master
      event: [ push ]
